---
- name: Common setup
  hosts: all
  become: yes
  tasks:
    - name: Disable SELinux (only if exists)
      command: setenforce 0
      ignore_errors: yes

    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
      ignore_errors: yes

- name: Setup frontend (nginx)
  hosts: frontend
  become: yes
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Configure nginx proxy
      copy:
        dest: /etc/nginx/conf.d/proxy.conf
        content: |
          server {
            listen 80;
            location / {
              proxy_pass http://{{ hostvars['u21.local'].ansible_host }}:19999/;
            }
          }
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

- name: Setup backend (Netdata)
  hosts: backend
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: software-properties-common
        state: present
        update_cache: yes

    - name: Install Netdata
      shell: bash <(curl -Ss https://my-netdata.io/kickstart.sh)

    - name: Ensure Netdata is running
      service:
        name: netdata
        state: started
        enabled: yes

